---
name: Config-IniHash
version: 3.01.00
author:
  - 'Jenda Krynicky <Jenda@Krynicky.cz>'
abstract: Perl extension for reading and writing INI files
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Hash::Case: 0
  Hash::WithDefaults: 0.04
provides:
  Config::IniHash:
    file: lib/Config/IniHash.pm
    version: 3.01.00
  Hash::Case::LowerX:
    file: lib/Config/IniHash.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
